# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name : Sync

variables:
MYPATH: $(myPAT)

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://$(MYPAT)@github.com/dejan995/hms-docker.git'
